USE [master]
GO

/****** Object:  Database [EOSDB]    Script Date: 07-03-2021 20:09:01 ******/
CREATE DATABASE [EOSDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EOSDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\EOSDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EOSDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\EOSDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EOSDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EOSDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EOSDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EOSDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EOSDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EOSDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EOSDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EOSDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EOSDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EOSDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EOSDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EOSDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EOSDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EOSDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EOSDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EOSDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EOSDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EOSDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EOSDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EOSDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EOSDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EOSDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EOSDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EOSDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EOSDB] SET  MULTI_USER 
GO

ALTER DATABASE [EOSDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EOSDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EOSDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EOSDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EOSDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EOSDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EOSDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EOSDB] SET  READ_WRITE 
GO


